"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const person_controllers_1 = require("../controllers/person.controllers");
const router = (0, express_1.Router)();
router.post("/persons", person_controllers_1.createPerson);
router.get("/persons", person_controllers_1.getPersons);
router.put('/persons/:id', person_controllers_1.updatePerson);
router.delete('/persons/:id', person_controllers_1.deletePerson);
router.get('/persons/:id', person_controllers_1.getPerson);
//router.get('http://localhost:4000/persons?sortBy=name%sortOrder=ASC', getPersonsNameAsc);
exports.default = router;
